"""Initial schema

Revision ID: 7f31df5271a9
Revises: 
Create Date: 2026-09-15 14:56:54.335986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f31df5271a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optimizer_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('solver_type', sa.String(), nullable=False),
    sa.Column('weight_config', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimizer_runs_id'), 'optimizer_runs', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('pickup_lat', sa.Float(), nullable=False),
    sa.Column('pickup_lng', sa.Float(), nullable=False),
    sa.Column('delivery_lat', sa.Float(), nullable=False),
    sa.Column('delivery_lng', sa.Float(), nullable=False),
    sa.Column('demand_weight', sa.Float(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'STANDARD', 'HIGH', 'URGENT', name='priority'), nullable=False),
    sa.Column('time_window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('service_time_minutes', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'IN_TRANSIT', 'DELIVERED', 'LATE', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('manager', 'researcher', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('capacity', sa.Float(), nullable=False),
    sa.Column('vehicle_type', sa.Enum('BIKE', 'CAR', 'VAN', 'TRUCK', name='vehicletype'), nullable=False),
    sa.Column('fuel_efficiency', sa.Float(), nullable=False),
    sa.Column('available_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('available_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_lat', sa.Float(), nullable=True),
    sa.Column('current_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('vehicle_id')
    )
    op.create_index(op.f('ix_vehicles_vehicle_id'), 'vehicles', ['vehicle_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('predicted_time_p10', sa.Float(), nullable=False),
    sa.Column('predicted_time_p50', sa.Float(), nullable=False),
    sa.Column('predicted_time_p90', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('shap_top_features', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('ordered_stops', sa.JSON(), nullable=False),
    sa.Column('predicted_arrival_times', sa.JSON(), nullable=False),
    sa.Column('total_distance_km', sa.Float(), nullable=False),
    sa.Column('total_predicted_time_min', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('optimizer_run_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['optimizer_run_id'], ['optimizer_runs.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_index(op.f('ix_routes_route_id'), 'routes', ['route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routes_route_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_vehicles_vehicle_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_optimizer_runs_id'), table_name='optimizer_runs')
    op.drop_table('optimizer_runs')
    # ### end Alembic commands ###
